apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: 'TCP'
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: 'TCP'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          imagePullPolicy: Always
          image: aleksander92/sb:v4
          env:
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: AUTH_ADDRESS
                  name: env-variables-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          imagePullPolicy: Always
          image: aleksander92/sb-users:v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-variables-map
data:
  AUTH_ADDRESS: 'users-service.default:8081'

