apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: 'TCP'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          imagePullPolicy: Always
          image: aleksander92/sb:v4
          env:
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: AUTH_ADDRESS
                  name: env-variables-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-variables-map
data:
  AUTH_ADDRESS: '127.0.0.1:63755'

