apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app # can select by only 1 label if we want to
  ports:
    - port: 80 # the outside world port
      targetPort: 8080 # the port my app is listening on
      protocol: 'TCP'
  type: LoadBalancer
